services:

  notes-ui:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - notes-api
    networks:
      - app-network

  notes-api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notes_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  postgres:
    image: postgres:18rc1
    container_name: notes_postgres_db
    restart: always
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge