version: "3.9"

services:
  postgres:
    image: postgres:18rc1
    container_name: notes_postgres_db
    restart: always
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: